### ISSUE TITLE
train_classifier.py res-cp 指令运算

### ISSUE THREAD

**Issue by ffufeng** [bupticybee/icyface_offline#2]
python3 train_classifier.py res-cp 这个指令会运算多少层，大概多长时间

**Comment by bupticybee** [comment]
我猜测你问的是resnet多少层，多少时间？
resnet34层，大概半天收敛完毕吧

**Comment by ffufeng** [comment]
好奇怪，我执行这个命令目前貌似已经到42层了，还有继续下去的趋势，也不知道要怎么终止，也担心直接终止又要从0开始

**Comment by bupticybee** [comment]
@ffufeng ffufeng

是这样的，你看代码里是没有停止条件的，所以你不把他停止他会一直训练下去，然而训练脚本里有一句：
```python
model = tflearn.DNN(reg,checkpoint_path='models/{}'.format(MODEL_FILE),max_checkpoints=100,session=sess)
```

每一轮的模型会储存在models目录下，你既然已经训练了42轮，就可以停止了，一般十几轮就可以停止了

**Comment by ffufeng** [comment]
明白了，谢谢啦！！
